export const returnMessages = Object.freeze({
  EmailInUse: 'Email is in use!',
  EmailPasswordValidation: 'Invalid password or email!',
  EmailNotVerified: 'Email is not verified!',
  UserSuccessfullyLoggedIn: 'You have been successfully logged in!',
  UserNotCreated: 'Something went wrong! User is not created!',
  UserAlreadyVerified: 'User is already verified',
  UserNotFound: 'User not found!',
  UserCodeNotFound: 'Code not found!',
  CodeNotValid: 'Code is not valid!',
  BadUserCode: 'Bad Code!',
  LimitReached: 'Limit reached!',
  CategoryNameLength: 'Category name must be between 1 and 50 characters!',
  CategoryAlreadyExists: 'News category already exists',
  CategoryNotFound: 'News category not found',
  TitleLength: 'Title length must be between 1 and 50 characters!',
  NewsNotFound: 'News not found',
  NewsNotDeleted: 'News not deleted',
  ImageIncorrectFormat: 'Image incorrect format',
  ImageNotFound: 'Image not found',
  SomethingWentWrong: 'Something went wrong',
  ResetTokenSent: 'Reset token sent successfully',
  InvalidResetToken: 'Invalid or expired reset token',
  PasswordReset: 'Password reset successfully',
  PasswordTooWeak:
    'Password too weak! Must contain minimum 6 characters, at least one UPPERCASE letter, one lowercase letter, one number, and one special character!',
});
